# Generated by Django 5.1 on 2024-08-24 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='recipeowner_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='recipeowner_permissions_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('type', models.CharField(max_length=50)),
                ('ingredients', models.JSONField()),
                ('method', models.JSONField()),
                ('categories', models.JSONField()),
                ('views', models.IntegerField(default=0)),
                ('rating', models.JSONField()),
                ('likes', models.ManyToManyField(blank=True, related_name='myLikes', to='recipes.recipeowner')),
                ('saved', models.ManyToManyField(blank=True, related_name='mySaved', to='recipes.recipeowner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipesPosted', to='recipes.recipeowner')),
            ],
        ),
    ]
