# Generated by Django 5.1 on 2024-08-24 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeowner',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipeowner',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following_set', to='recipes.recipeowner'),
        ),
        migrations.AddField(
            model_name='recipeowner',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers_set', to='recipes.recipeowner'),
        ),
        migrations.AddField(
            model_name='recipeowner',
            name='liked_recipes',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='recipeowner',
            name='profileImage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipeowner',
            name='recipes_posted',
            field=models.ManyToManyField(blank=True, related_name='posted_by', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='recipeowner',
            name='saved_recipes',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='recipeowner',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_recipes_set', to='recipes.recipeowner'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved_recipes_set', to='recipes.recipeowner'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_created', to='recipes.recipeowner'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipeowner',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='recipeowner_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='recipeowner',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='recipeowner_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
