# Generated by Django 5.1 on 2024-08-25 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipeowner_bio_recipeowner_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='saved',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='likes',
        ),
        migrations.DeleteModel(
            name='RecipeOwner',
        ),
    ]
