# Generated by Django 5.1 on 2024-08-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('recipes', '0004_recipe_likes_recipe_saved_recipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_recipes_set', to='accounts.recipeowner'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved_recipes_set', to='accounts.recipeowner'),
        ),
    ]
