# Generated by Django 5.1 on 2024-08-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_likes_alter_recipe_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='saved',
        ),
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='saved',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
