# Generated by Django 5.1 on 2024-08-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_recipe_likes_remove_recipe_saved_reciperating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='rating',
        ),
        migrations.AddField(
            model_name='recipe',
            name='rating',
            field=models.ManyToManyField(blank=True, related_name='ratings', to='recipes.reciperating'),
        ),
    ]
